### ISSUE TITLE
tensorflow and anaconda DisplayFractal(ns.eval()) fail

### ISSUE THREAD

**Issue by tobigithub** [tobigithub/tensorflow-deep-learning#6]
Running the [mandelbrot example](https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/tutorials/mandelbrot/index.md) using source code from [tensorflow-deep-learning](https://github.com/tobigithub/tensorflow-deep-learning/blob/master/examples/mandelbrot-tensorflow.py) repository fails with

```
>>> DisplayFractal(ns.eval())
<IPython.core.display.Image object>
In : 
```

This is a fresh install of Ubuntu 14 LTE with all upgrades and all updates and a fresh install of Anaconda python 2.7 Anaconda2-2.4.0-Linux-x86_64.sh

**Comment by pyaf** [comment]
I tried it with jupyter notebook and it worked!!
`conda install jupyter`
`jupyter notebook`

then load your python file and run!
